services:
  backend:
    image: ghcr.io/lakyn80/vkorni-backend:latest
    volumes:
      - backend_photos:/app/static/photos
      - backend_accepted_images:/app/static/accepted_images
      - backend_rejected_images:/app/static/rejected_images
      - backend_data:/app/app/data
      - backend_chroma:/app/chroma_data
    ports:
      - "8020:8000"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  worker:
    image: ghcr.io/lakyn80/vkorni-backend:latest
    command: rq worker bios images --url ${REDIS_URL}
    volumes:
      - backend_photos:/app/static/photos
      - backend_accepted_images:/app/static/accepted_images
      - backend_rejected_images:/app/static/rejected_images
      - backend_data:/app/app/data
      - backend_chroma:/app/chroma_data
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: ghcr.io/lakyn80/vkorni-frontend:latest
    ports:
      - "3014:3000"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: vkorni-redis
    ports:
      - "6382:6379"
    restart: unless-stopped

volumes:
  backend_photos:
  backend_accepted_images:
  backend_rejected_images:
  backend_data:
  backend_chroma:
