"use client";

import { normalizePhotoUrl } from "@/utils/photos";
import type { Profile } from "@/types";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "http://localhost:8020";

type Props = {
  profile: Profile;
  onDrop: (e: React.DragEvent<HTMLDivElement>) => void;
};

export function MemorialFrame({ profile, onDrop }: Props) {
  const framedUrl = profile.framedPhotoUrl
    ? `${API_BASE}${profile.framedPhotoUrl}${profile.framedPreviewVersion ? `?v=${profile.framedPreviewVersion}` : ""}`
    : null;

  return (
    <div className="border-t border-ink/10 pt-6">
      <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-ink/40">
        Мемориальная карточка
      </p>

      <div
        className="overflow-hidden rounded-2xl"
        onDragOver={(e) => e.preventDefault()}
        onDrop={onDrop}
      >
        {framedUrl ? (
          /* Framed portrait generated by backend — this is what gets sent to vkorni.com */
          <div className="flex flex-col items-center gap-3">
            <img
              src={framedUrl}
              alt={profile.name}
              className="w-full max-w-md rounded-xl shadow-2xl"
              style={{ imageRendering: "auto" }}
            />
            <p className="text-xs text-ink/30">
              Это изображение будет отправлено на vkorni.com
            </p>
          </div>
        ) : profile.selectedPhoto ? (
          /* Fallback: original photo while frame is generating */
          <div className="flex flex-col items-center gap-2">
            <img
              src={normalizePhotoUrl(profile.selectedPhoto)}
              alt={profile.name}
              className="w-full max-w-md rounded-xl opacity-60"
            />
            <p className="text-xs text-ink/40 animate-pulse">Генерация рамки…</p>
          </div>
        ) : (
          /* No photo yet */
          <div
            className="flex min-h-[200px] flex-col items-center justify-center gap-3 rounded-xl"
            style={{ background: "rgba(255,255,255,0.03)", border: "1px dashed rgba(255,255,255,0.1)" }}
          >
            <span className="text-3xl opacity-40">🕯️</span>
            <p className="text-xs text-white/30">Перетащите фото сюда</p>
          </div>
        )}
      </div>
    </div>
  );
}
